#!/bin/bash
# Shows a loading indicator whilst executing another command.
## 5 styles available [0-4].
### Can set to `$STYLE_ID=$(($RANDOM % 4))` if want random indicator
# @args any command or process to run whilst showing loading indicator. 
## eg: `./loading sleep 5`
STYLE_ID=4

function setAnimation() {
  case $STYLE_ID in
  0)
    ANIMATION="▁▂▃▄▅▆▇█▇▆▅▄▃▂▁"
    ;;
  1)
    ANIMATION="▉▊▋▌▍▎▏▎▍▌▋▊▉"
    ;;
  2)
    ANIMATION='▖▘▝▗'
    ;;
  
  3)
    ANIMATION='◢◣◤◥'
    ;;
  4)
    ANIMATION='⣾⣽⣻⢿⡿⣟⣯⣷'
    ;;
  esac
}

function loading() {
  local LC_CTYPE=C # non-unicode locale 
  local charwidth=3
  local pid=$1 # Process Id - previous command
  setAnimation

  local i=0
  while kill -0 $pid 2>/dev/null; do
    local i=$(((i + $charwidth) % ${#ANIMATION}))
    printf "%s" "${ANIMATION:$i:$charwidth}"
    echo -en "\033[$1D" # Resets cursor
    sleep .1
  done
  wait $pid # exit code
  return $?
}
("$@") &
loading $!
